import type { Archetype } from "./types";

export const ARCHETYPES: readonly Archetype[] = [
  {
    id: "void",
    name: "The Void",
    shadeAnchor: 3,
    blurb: "A profile so dark it is mostly theoretical.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: -1,
      victim_victimless: -1,
      self_other: 1,
      calculated_spontaneous: 0,
      ideological_opportunistic: 1,
      private_performative: -1,
      upward_downward: 1,
      active_omissive: -1,
      realist_absolutist: -1,
    },
  },
  {
    id: "career_criminal",
    name: "The Career Criminal",
    shadeAnchor: 12,
    blurb: "Gray is the job, not the occasional lapse.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: -1,
      victim_victimless: -0.8,
      self_other: 1,
      calculated_spontaneous: -0.5,
      ideological_opportunistic: 1,
      private_performative: -1,
      active_omissive: -1,
      realist_absolutist: -1,
    },
  },
  {
    id: "silent_smuggler",
    name: "The Silent Smuggler",
    shadeAnchor: 16,
    blurb: "Moves things across lines, quietly and profitably.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: -0.7,
      victim_victimless: 0.4,
      calculated_spontaneous: -1,
      ideological_opportunistic: 1,
      private_performative: -1,
      upward_downward: -0.8,
      active_omissive: -1,
      realist_absolutist: -1,
    },
  },
  {
    id: "ideological_outlaw",
    name: "The Ideological Outlaw",
    shadeAnchor: 20,
    blurb: "Breaks the law for the cause, and will tell you why.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -1,
      victim_victimless: 0.2,
      self_other: -0.3,
      ideological_opportunistic: -1,
      private_performative: 0.3,
      upward_downward: -1,
      active_omissive: -1,
      realist_absolutist: -0.7,
    },
  },
  {
    id: "street_fixer",
    name: "The Street Fixer",
    shadeAnchor: 22,
    blurb: "Keeps the block running by knowing which rules to skip.",
    axes: {
      principled_pragmatic: 0.7,
      rebel_conformist: -0.6,
      victim_victimless: 0,
      self_other: 0.2,
      calculated_spontaneous: 0.3,
      ideological_opportunistic: 0.5,
      private_performative: -0.4,
      active_omissive: -1,
    },
  },
  {
    id: "silent_activist",
    name: "The Silent Activist",
    shadeAnchor: 25,
    blurb: "Sabotage without a banner, principle without applause.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -1,
      victim_victimless: 0.6,
      self_other: -0.6,
      calculated_spontaneous: -0.8,
      ideological_opportunistic: -1,
      private_performative: -1,
      upward_downward: -1,
      active_omissive: -1,
      realist_absolutist: -0.8,
    },
  },
  {
    id: "revolutionary",
    name: "The Revolutionary",
    shadeAnchor: 28,
    blurb: "Everything is theatre and everything is political.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -1,
      victim_victimless: -0.3,
      ideological_opportunistic: -1,
      private_performative: 1,
      upward_downward: -1,
      active_omissive: -1,
      realist_absolutist: -1,
    },
  },
  {
    id: "righteous_vigilante",
    name: "The Righteous Vigilante",
    shadeAnchor: 28,
    blurb: "Harms the bad guys so you don't have to.",
    axes: {
      principled_pragmatic: -0.7,
      rebel_conformist: -0.8,
      victim_victimless: -1,
      self_other: 1,
      calculated_spontaneous: -0.5,
      ideological_opportunistic: -0.7,
      private_performative: 0.3,
      upward_downward: 0.5,
      active_omissive: -1,
    },
  },
  {
    id: "addict_orbit",
    name: "The Addict's Orbit",
    shadeAnchor: 22,
    blurb: "Gray is not a choice here, it's gravity.",
    axes: {
      principled_pragmatic: 0.4,
      rebel_conformist: -0.3,
      victim_victimless: 0.3,
      self_other: -1,
      calculated_spontaneous: 1,
      ideological_opportunistic: 1,
      private_performative: -0.6,
      active_omissive: -0.5,
    },
  },
  {
    id: "black_market_native",
    name: "The Black-Market Native",
    shadeAnchor: 30,
    blurb: "Grew up knowing which websites actually have the thing.",
    axes: {
      principled_pragmatic: 0.8,
      rebel_conformist: -0.5,
      victim_victimless: 1,
      calculated_spontaneous: -0.4,
      ideological_opportunistic: 0.7,
      private_performative: -0.8,
      active_omissive: -1,
      realist_absolutist: -1,
    },
  },
  {
    id: "gray_entrepreneur",
    name: "The Gray Entrepreneur",
    shadeAnchor: 32,
    blurb: "Moves first, reads the statute later, shrugs sometimes.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: -0.4,
      victim_victimless: 0.3,
      calculated_spontaneous: -0.8,
      ideological_opportunistic: 0.6,
      private_performative: 0.5,
      upward_downward: -0.5,
      active_omissive: -1,
    },
  },
  {
    id: "domestic_fraudster",
    name: "The Domestic Fraudster",
    shadeAnchor: 28,
    blurb: "Paperwork is a scalpel in the right hands.",
    axes: {
      principled_pragmatic: 0.8,
      rebel_conformist: 0.3,
      victim_victimless: -0.7,
      self_other: 1,
      calculated_spontaneous: -1,
      ideological_opportunistic: 0.8,
      private_performative: -1,
      upward_downward: 0.5,
      active_omissive: -1,
    },
  },
  {
    id: "crypto_pirate",
    name: "The Crypto Pirate",
    shadeAnchor: 36,
    blurb: "Every torrent is a vote against the model.",
    axes: {
      principled_pragmatic: 0.3,
      rebel_conformist: -0.7,
      victim_victimless: 0.8,
      calculated_spontaneous: -0.6,
      ideological_opportunistic: -0.2,
      private_performative: -0.5,
      upward_downward: -0.7,
      active_omissive: -0.6,
      realist_absolutist: -1,
    },
  },
  {
    id: "protest_vanguard",
    name: "The Protest Vanguard",
    shadeAnchor: 32,
    blurb: "First row, pepper spray in hair, bail money ready.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -1,
      victim_victimless: 0.2,
      self_other: -0.7,
      ideological_opportunistic: -1,
      private_performative: 0.7,
      upward_downward: -1,
      active_omissive: -1,
    },
  },
  {
    id: "squatter",
    name: "The Squatter",
    shadeAnchor: 35,
    blurb: "Empty buildings make no sense while anyone's cold.",
    axes: {
      principled_pragmatic: -0.4,
      rebel_conformist: -0.9,
      victim_victimless: 0.5,
      self_other: -0.2,
      calculated_spontaneous: -0.2,
      ideological_opportunistic: -0.7,
      private_performative: 0.2,
      upward_downward: -0.8,
      active_omissive: -0.7,
    },
  },
  {
    id: "street_philosopher",
    name: "The Street Philosopher",
    shadeAnchor: 38,
    blurb: "Every vice has a Nietzsche quote ready to go.",
    axes: {
      principled_pragmatic: -0.5,
      rebel_conformist: -0.6,
      victim_victimless: 0.7,
      self_other: -1,
      ideological_opportunistic: -0.6,
      private_performative: 0.5,
      realist_absolutist: -1,
    },
  },
  {
    id: "loud_vegan",
    name: "The Loud Vegan",
    shadeAnchor: 38,
    blurb: "Trespass for chickens counts as civic duty.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -0.6,
      victim_victimless: -1,
      self_other: -0.3,
      ideological_opportunistic: -1,
      private_performative: 1,
      active_omissive: -1,
    },
  },
  {
    id: "coffee_shop_regular",
    name: "The Coffee-Shop Regular",
    shadeAnchor: 40,
    blurb: "Technically legal here, morally legal everywhere, supposedly.",
    axes: {
      principled_pragmatic: 0.5,
      rebel_conformist: -0.2,
      victim_victimless: 1,
      self_other: -1,
      calculated_spontaneous: 0.4,
      ideological_opportunistic: 0.7,
      private_performative: -0.3,
      realist_absolutist: -0.7,
    },
  },
  {
    id: "honest_pirate",
    name: "The Honest Pirate",
    shadeAnchor: 42,
    blurb: "Downloads first, buys merch later, sleeps fine.",
    axes: {
      principled_pragmatic: 0.4,
      rebel_conformist: -0.4,
      victim_victimless: 0.7,
      calculated_spontaneous: -0.3,
      private_performative: -0.5,
      active_omissive: -0.3,
      realist_absolutist: -0.7,
    },
  },
  {
    id: "civil_disobedient",
    name: "The Civil Disobedient",
    shadeAnchor: 33,
    blurb: "Gets arrested on purpose, politely.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: -0.9,
      victim_victimless: 0.5,
      self_other: -0.8,
      calculated_spontaneous: -0.7,
      ideological_opportunistic: -1,
      private_performative: 0.8,
      upward_downward: -1,
      active_omissive: -1,
    },
  },
  {
    id: "tax_gymnast",
    name: "The Tax Gymnast",
    shadeAnchor: 40,
    blurb: "Every bracket is a dance floor.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: 0.4,
      victim_victimless: 0.7,
      self_other: 0.5,
      calculated_spontaneous: -1,
      ideological_opportunistic: 0.8,
      private_performative: -1,
      upward_downward: -0.5,
      active_omissive: 0,
    },
  },
  {
    id: "loophole_hunter",
    name: "The Loophole Hunter",
    shadeAnchor: 42,
    blurb: "Reads terms-of-service for sport.",
    axes: {
      principled_pragmatic: 0.9,
      rebel_conformist: 0.3,
      victim_victimless: 0.8,
      calculated_spontaneous: -1,
      ideological_opportunistic: 0.7,
      private_performative: -0.4,
      upward_downward: -0.3,
    },
  },
  {
    id: "hustler",
    name: "The Hustler",
    shadeAnchor: 45,
    blurb: "The side gig has a side gig. Nothing personal.",
    axes: {
      principled_pragmatic: 1,
      rebel_conformist: -0.2,
      victim_victimless: 0.4,
      calculated_spontaneous: 0.2,
      ideological_opportunistic: 0.8,
      private_performative: -0.2,
      realist_absolutist: -0.5,
    },
  },
  {
    id: "moral_pragmatist",
    name: "The Moral Pragmatist",
    shadeAnchor: 48,
    blurb: "It depends. It always depends.",
    axes: {
      principled_pragmatic: 0.6,
      rebel_conformist: 0.1,
      calculated_spontaneous: -0.3,
      ideological_opportunistic: 0.4,
      private_performative: -0.3,
      realist_absolutist: -0.5,
    },
  },
  {
    id: "true_gray",
    name: "True Gray",
    shadeAnchor: 50,
    blurb: "The exact middle, calibrated to the national mean.",
    axes: {
      principled_pragmatic: 0,
      rebel_conformist: 0,
      victim_victimless: 0,
      self_other: 0,
      calculated_spontaneous: 0,
      ideological_opportunistic: 0,
      private_performative: 0,
      upward_downward: 0,
      active_omissive: 0,
      realist_absolutist: 0,
    },
  },
  {
    id: "fietser_door_rood",
    name: "The Fietser Door Rood",
    shadeAnchor: 58,
    blurb: "One small gray per intersection, daily. Very Dutch.",
    axes: {
      principled_pragmatic: 0.6,
      rebel_conformist: -0.4,
      victim_victimless: 0.5,
      self_other: -0.6,
      calculated_spontaneous: 0.7,
      ideological_opportunistic: 0.7,
      private_performative: -0.6,
      active_omissive: -0.5,
      realist_absolutist: -0.7,
    },
  },
  {
    id: "parking_rebel",
    name: "The Parking Rebel",
    shadeAnchor: 60,
    blurb: "Ten minutes won't hurt anybody. Twenty, then, fine.",
    axes: {
      principled_pragmatic: 0.7,
      rebel_conformist: -0.2,
      victim_victimless: 0.6,
      self_other: 0.2,
      calculated_spontaneous: 0.5,
      ideological_opportunistic: 0.8,
      private_performative: -0.7,
    },
  },
  {
    id: "suburban_chancer",
    name: "The Suburban Chancer",
    shadeAnchor: 62,
    blurb: "Good lawn, mediocre tax return, occasional fib.",
    axes: {
      principled_pragmatic: 0.7,
      rebel_conformist: 0.4,
      victim_victimless: 0.3,
      self_other: 0.3,
      calculated_spontaneous: 0.3,
      ideological_opportunistic: 0.8,
      private_performative: -0.8,
    },
  },
  {
    id: "white_lies_diplomat",
    name: "The White-Lies Diplomat",
    shadeAnchor: 60,
    blurb: "Lies kindly, frequently, for social lubrication.",
    axes: {
      principled_pragmatic: 0.6,
      rebel_conformist: 0.3,
      victim_victimless: 0.2,
      self_other: 0.3,
      calculated_spontaneous: -0.4,
      ideological_opportunistic: 0.6,
      private_performative: -0.2,
      upward_downward: 0,
    },
  },
  {
    id: "law_abiding_cynic",
    name: "The Law-Abiding Cynic",
    shadeAnchor: 65,
    blurb: "Plays by rules they don't believe in.",
    axes: {
      principled_pragmatic: -0.2,
      rebel_conformist: 0.7,
      ideological_opportunistic: 0.3,
      private_performative: -0.6,
      active_omissive: 0.8,
      realist_absolutist: -0.8,
    },
  },
  {
    id: "moral_gossip",
    name: "The Moral Gossip",
    shadeAnchor: 58,
    blurb: "Knows everyone's sins, shares them for our own good.",
    axes: {
      principled_pragmatic: 0.5,
      rebel_conformist: 0.4,
      victim_victimless: -0.8,
      self_other: 1,
      calculated_spontaneous: -0.2,
      ideological_opportunistic: 0.5,
      private_performative: 0.8,
      upward_downward: 0.6,
      active_omissive: -0.4,
    },
  },
  {
    id: "weekender_libertine",
    name: "The Weekender Libertine",
    shadeAnchor: 62,
    blurb: "Saturday night is a different legal regime.",
    axes: {
      principled_pragmatic: 0.4,
      rebel_conformist: -0.1,
      victim_victimless: 0.8,
      self_other: -0.9,
      calculated_spontaneous: 0.8,
      ideological_opportunistic: 0.7,
      private_performative: -0.2,
      realist_absolutist: -0.6,
    },
  },
  {
    id: "quiet_resister",
    name: "The Quiet Resister",
    shadeAnchor: 65,
    blurb: "Says no softly, slows things down, stays unreadable.",
    axes: {
      principled_pragmatic: -0.7,
      rebel_conformist: -0.3,
      victim_victimless: 0.4,
      self_other: -0.3,
      calculated_spontaneous: -0.6,
      ideological_opportunistic: -0.7,
      private_performative: -1,
      upward_downward: -0.5,
      active_omissive: 0.5,
    },
  },
  {
    id: "moral_centrist",
    name: "The Moral Centrist",
    shadeAnchor: 62,
    blurb: "Both sides, mostly, comfortably.",
    axes: {
      principled_pragmatic: 0.2,
      rebel_conformist: 0.5,
      private_performative: -0.5,
      realist_absolutist: -0.3,
    },
  },
  {
    id: "armchair_radical",
    name: "The Armchair Radical",
    shadeAnchor: 65,
    blurb: "Fury online, mild offline, never arrested for anything.",
    axes: {
      principled_pragmatic: -0.6,
      rebel_conformist: 0.6,
      ideological_opportunistic: -0.7,
      private_performative: 0.9,
      upward_downward: -0.7,
      active_omissive: 0.8,
    },
  },
  {
    id: "good_citizen_with_footnotes",
    name: "The Good Citizen with Footnotes",
    shadeAnchor: 70,
    blurb: "Law-abiding, but has thought experiments.",
    axes: {
      principled_pragmatic: -0.5,
      rebel_conformist: 0.7,
      calculated_spontaneous: -0.7,
      private_performative: -0.7,
      realist_absolutist: 0.3,
    },
  },
  {
    id: "tax_compliant",
    name: "The Tax Compliant",
    shadeAnchor: 70,
    blurb: "Pays the full bill on principle and fear in equal part.",
    axes: {
      principled_pragmatic: -0.3,
      rebel_conformist: 0.8,
      calculated_spontaneous: -0.8,
      ideological_opportunistic: -0.4,
      private_performative: -0.8,
      realist_absolutist: 0.6,
    },
  },
  {
    id: "silent_ethicist",
    name: "The Silent Ethicist",
    shadeAnchor: 75,
    blurb: "Has a rubric, wouldn't bore you with it.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: 0.3,
      calculated_spontaneous: -1,
      ideological_opportunistic: -0.8,
      private_performative: -1,
      realist_absolutist: -0.2,
    },
  },
  {
    id: "dutiful_accountant",
    name: "The Dutiful Accountant",
    shadeAnchor: 78,
    blurb: "Rows tidy, ledgers clean, conscience audited monthly.",
    axes: {
      principled_pragmatic: -0.4,
      rebel_conformist: 0.9,
      calculated_spontaneous: -1,
      ideological_opportunistic: -0.3,
      private_performative: -0.8,
      active_omissive: -0.3,
      realist_absolutist: 0.7,
    },
  },
  {
    id: "institutionalist",
    name: "The Institutionalist",
    shadeAnchor: 80,
    blurb: "Defends the rules because the rules made the life possible.",
    axes: {
      principled_pragmatic: -0.6,
      rebel_conformist: 1,
      ideological_opportunistic: -0.5,
      private_performative: 0.4,
      upward_downward: 0.5,
      active_omissive: -0.6,
      realist_absolutist: 1,
    },
  },
  {
    id: "rule_maker",
    name: "The Rule-Maker",
    shadeAnchor: 78,
    blurb: "Writes the thing you comply with. Mostly complies too.",
    axes: {
      principled_pragmatic: 0.2,
      rebel_conformist: 0.7,
      calculated_spontaneous: -1,
      ideological_opportunistic: -0.2,
      private_performative: 0.6,
      upward_downward: 0.8,
      active_omissive: -0.8,
      realist_absolutist: 0.6,
    },
  },
  {
    id: "letter_of_law",
    name: "The Letter-of-the-Law Absolutist",
    shadeAnchor: 82,
    blurb: "Spirit, letter — letter wins.",
    axes: {
      principled_pragmatic: -0.9,
      rebel_conformist: 1,
      calculated_spontaneous: -0.8,
      ideological_opportunistic: -0.8,
      private_performative: 0.2,
      realist_absolutist: 1,
    },
  },
  {
    id: "straight_arrow",
    name: "The Straight Arrow",
    shadeAnchor: 85,
    blurb: "Means it. No angle, no irony, no gray corners.",
    axes: {
      principled_pragmatic: -0.9,
      rebel_conformist: 0.9,
      private_performative: -0.7,
      active_omissive: -0.5,
      realist_absolutist: 0.8,
    },
  },
  {
    id: "holier_than_thou",
    name: "The Holier-Than-Thou",
    shadeAnchor: 85,
    blurb: "Virtuous, keen that you notice.",
    axes: {
      principled_pragmatic: -0.8,
      rebel_conformist: 0.7,
      victim_victimless: -0.5,
      self_other: 0.8,
      private_performative: 1,
      upward_downward: 0.7,
      active_omissive: -0.6,
    },
  },
  {
    id: "perfect_neighbor",
    name: "The Perfect Neighbor",
    shadeAnchor: 85,
    blurb: "Home association board, silent curtain twitch, clean tax.",
    axes: {
      principled_pragmatic: -0.2,
      rebel_conformist: 0.9,
      self_other: 0.6,
      calculated_spontaneous: -0.7,
      ideological_opportunistic: 0.2,
      private_performative: 0.3,
      upward_downward: 0.5,
      active_omissive: -0.3,
      realist_absolutist: 0.6,
    },
  },
  {
    id: "moral_bystander",
    name: "The Moral Bystander",
    shadeAnchor: 85,
    blurb: "Clean hands, averted eyes, perfect receipts.",
    axes: {
      rebel_conformist: 1,
      private_performative: -0.8,
      active_omissive: 1,
      realist_absolutist: 0.5,
    },
  },
  {
    id: "quiet_saint",
    name: "The Quiet Saint",
    shadeAnchor: 92,
    blurb: "Unusually good. Doesn't mention it.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: 0.7,
      self_other: -0.8,
      calculated_spontaneous: -0.5,
      ideological_opportunistic: -0.9,
      private_performative: -1,
      upward_downward: -0.3,
      active_omissive: 0.2,
      realist_absolutist: 0.5,
    },
  },
  {
    id: "cloistered",
    name: "The Cloistered",
    shadeAnchor: 95,
    blurb: "Withdrawn so far from temptation the gray can't reach.",
    axes: {
      rebel_conformist: 0.8,
      private_performative: -1,
      active_omissive: 1,
      realist_absolutist: 0.4,
    },
  },
  {
    id: "pristine",
    name: "Pristine",
    shadeAnchor: 98,
    blurb: "Statistically improbable. Sleeping exceptionally well.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: 1,
      calculated_spontaneous: -0.8,
      ideological_opportunistic: -1,
      private_performative: -0.7,
      realist_absolutist: 1,
    },
  },
  {
    id: "aspirational_absolute",
    name: "The Aspirational Absolute",
    shadeAnchor: 100,
    blurb: "Hypothetical. Nobody scores here and means it.",
    axes: {
      principled_pragmatic: -1,
      rebel_conformist: 1,
      victim_victimless: 1,
      self_other: -1,
      calculated_spontaneous: -1,
      ideological_opportunistic: -1,
      private_performative: -1,
      upward_downward: -1,
      active_omissive: -1,
      realist_absolutist: 1,
    },
  },
] as const;

export function archetypeById(id: string): Archetype | undefined {
  return ARCHETYPES.find((a) => a.id === id);
}
