import type { Question } from "@/lib/scoring";
import { BINARY, likert } from "./likert";

export const NL_QUESTIONS: readonly Question[] = [
  {
    id: "nl.fiets-rood",
    prompt: "How often do you cycle through a red light?",
    format: "likert",
    severity: { nl: 3 },
    axes: {
      rebel_conformist: -0.4,
      victim_victimless: 0.7,
      self_other: -0.3,
      calculated_spontaneous: 0.6,
      realist_absolutist: -0.5,
    },
    answers: likert(),
    citation: {
      nl: {
        statute: "RVV 1990 art. 62",
        note: "Traffic signs apply to cyclists.",
      },
    },
    tags: ["traffic", "everyday"],
  },
  {
    id: "nl.speeding",
    prompt: "How often do you drive more than 20 km/h over the speed limit?",
    format: "likert",
    severity: { nl: 8 },
    axes: {
      victim_victimless: -0.2,
      self_other: 0.3,
      calculated_spontaneous: 0.3,
      ideological_opportunistic: 0.5,
      realist_absolutist: -0.4,
    },
    answers: likert(),
    citation: { nl: { statute: "Wegenverkeerswet art. 20 · RVV 1990" } },
    tags: ["traffic", "everyday"],
  },
  {
    id: "nl.piracy",
    prompt:
      "How often do you download or stream pirated movies, shows, music, or software?",
    format: "likert",
    severity: { nl: 5 },
    axes: {
      rebel_conformist: -0.3,
      victim_victimless: 0.6,
      self_other: 0.2,
      ideological_opportunistic: 0.2,
      realist_absolutist: -0.7,
    },
    answers: likert(),
    citation: { nl: { statute: "Auteurswet art. 45" } },
    tags: ["digital", "everyday"],
  },
  {
    id: "nl.weed-public",
    prompt: "How often do you smoke weed in public, outside a coffee shop?",
    format: "likert",
    severity: { nl: 4 },
    axes: {
      rebel_conformist: -0.3,
      victim_victimless: 0.6,
      self_other: -0.5,
      calculated_spontaneous: 0.5,
      realist_absolutist: -0.6,
    },
    answers: likert(),
    citation: {
      nl: {
        statute: "Opiumwet art. 3 (lijst II)",
        note: "Possession under 5g is tolerated; public use is locally restricted.",
      },
    },
    tags: ["drugs", "NL-specific"],
  },
  {
    id: "nl.hard-drugs",
    prompt:
      "How often do you use hard drugs (lijst I under the Opiumwet — e.g. MDMA, cocaine, heroin)?",
    format: "likert",
    severity: { nl: 25 },
    axes: {
      rebel_conformist: -0.3,
      victim_victimless: 0.3,
      self_other: -0.8,
      calculated_spontaneous: 0.3,
      ideological_opportunistic: 0.3,
      realist_absolutist: -0.5,
    },
    answers: likert(),
    citation: { nl: { statute: "Opiumwet art. 2 (lijst I)" } },
    tags: ["drugs"],
  },
  {
    id: "nl.bike-drunk",
    prompt: "How often do you cycle home after more than two drinks?",
    format: "likert",
    severity: { nl: 8 },
    axes: {
      self_other: -0.4,
      calculated_spontaneous: 0.5,
      ideological_opportunistic: 0.5,
      realist_absolutist: -0.4,
    },
    answers: likert(),
    citation: {
      nl: { statute: "WVW art. 8", note: "DUI rules apply to bicycles." },
    },
    tags: ["traffic", "NL-specific"],
  },
  {
    id: "nl.jaywalk",
    prompt: "How often do you cross on a red pedestrian signal?",
    format: "likert",
    severity: { nl: 1 },
    axes: {
      rebel_conformist: -0.2,
      victim_victimless: 0.9,
      self_other: -0.1,
      calculated_spontaneous: 0.7,
      realist_absolutist: -0.6,
    },
    answers: likert(),
    citation: { nl: { statute: "RVV 1990 art. 49" } },
    tags: ["traffic", "everyday"],
  },
  {
    id: "nl.form-lies",
    prompt:
      "How often do you round, omit, or stretch the truth on official forms — taxes, benefits, insurance, gemeente?",
    format: "likert",
    severity: { nl: 18 },
    axes: {
      principled_pragmatic: 0.7,
      victim_victimless: 0.2,
      self_other: 0.4,
      calculated_spontaneous: -0.5,
      ideological_opportunistic: 0.6,
      private_performative: -0.7,
      upward_downward: -0.3,
    },
    answers: likert(),
    citation: {
      nl: { statute: "Sr art. 225", note: "Valsheid in geschrifte." },
    },
    tags: ["fraud", "paperwork"],
  },
  {
    id: "nl.zwart-werk",
    prompt: "How often do you work or pay cash for work that goes undeclared?",
    format: "likert",
    severity: { nl: 15 },
    axes: {
      principled_pragmatic: 0.7,
      rebel_conformist: -0.2,
      victim_victimless: 0.3,
      self_other: 0.3,
      calculated_spontaneous: -0.2,
      ideological_opportunistic: 0.5,
      private_performative: -0.7,
      realist_absolutist: -0.5,
    },
    answers: likert(),
    citation: { nl: { statute: "Wet op de loonbelasting 1964 · Sr art. 225" } },
    tags: ["fraud", "labor"],
  },
  {
    id: "nl.adblock-revenue",
    prompt:
      "How often do you use an ad-blocker on sites that clearly depend on ads to exist?",
    format: "likert",
    severity: { nl: 1 },
    axes: {
      victim_victimless: 0.5,
      self_other: 0.3,
      ideological_opportunistic: 0.3,
      realist_absolutist: -0.5,
    },
    answers: likert(),
    tags: ["digital", "everyday"],
  },
  {
    id: "nl.streaming-sharing",
    prompt:
      "How often do you use someone else's paid streaming account (Netflix, Spotify, etc.)?",
    format: "likert",
    severity: { nl: 2 },
    axes: {
      victim_victimless: 0.7,
      self_other: 0.2,
      ideological_opportunistic: 0.5,
      realist_absolutist: -0.5,
    },
    answers: likert(),
    citation: { nl: { statute: "Auteurswet · civil (contract breach)" } },
    tags: ["digital", "everyday"],
  },
  {
    id: "nl.white-lies-partner",
    prompt:
      "How often do you lie to a partner or close family about something they'd want to know?",
    format: "likert",
    severity: { nl: 5 },
    axes: {
      principled_pragmatic: 0.6,
      self_other: 0.5,
      calculated_spontaneous: -0.3,
      ideological_opportunistic: 0.5,
      private_performative: -0.6,
    },
    answers: likert(),
    tags: ["interpersonal", "non-criminal"],
  },
  {
    id: "nl.assault",
    prompt:
      "Have you ever physically assaulted another person outside of clear self-defense?",
    format: "binary",
    severity: { nl: 60 },
    axes: {
      victim_victimless: -1,
      self_other: 1,
      calculated_spontaneous: 0.2,
      private_performative: -0.3,
      active_omissive: -1,
    },
    answers: BINARY,
    citation: { nl: { statute: "Sr art. 300" } },
    tags: ["violence", "severe"],
  },
  {
    id: "nl.non-consent",
    prompt:
      "Have you ever engaged in a sexual act where clear, ongoing consent was absent?",
    format: "binary",
    severity: { nl: 90 },
    axes: {
      victim_victimless: -1,
      self_other: 1,
      private_performative: -0.7,
      active_omissive: -1,
    },
    answers: BINARY,
    citation: { nl: { statute: "Sr art. 242 · art. 246 · art. 249" } },
    tags: ["violence", "severe"],
  },
  {
    id: "nl.benefit-fraud",
    prompt:
      "Have you ever knowingly claimed a benefit, allowance, or insurance payout you weren't entitled to (over roughly €500)?",
    format: "binary",
    severity: { nl: 40 },
    axes: {
      principled_pragmatic: 0.8,
      victim_victimless: 0.2,
      self_other: 0.4,
      calculated_spontaneous: -0.6,
      ideological_opportunistic: 0.7,
      private_performative: -0.8,
      upward_downward: -0.3,
      active_omissive: -0.7,
    },
    answers: BINARY,
    citation: { nl: { statute: "Sr art. 326 (oplichting) · Sr art. 227b" } },
    tags: ["fraud"],
  },
  {
    id: "nl.self-defense",
    prompt: "Have you ever hit or restrained someone who was attacking you?",
    format: "binary",
    severity: { nl: 6 },
    axes: {
      calculated_spontaneous: 0.5,
      self_other: 0.3,
      active_omissive: -0.7,
      realist_absolutist: -0.3,
    },
    answers: BINARY,
    citation: {
      nl: { statute: "Sr art. 41", note: "Noodweer — legal if proportional." },
    },
    tags: ["violence", "lawful"],
  },
  {
    id: "nl.drug-dealing",
    prompt: "Have you ever sold drugs (of any kind) for profit?",
    format: "binary",
    severity: { nl: 55 },
    axes: {
      principled_pragmatic: 0.5,
      rebel_conformist: -0.4,
      victim_victimless: 0.2,
      self_other: 0.2,
      calculated_spontaneous: -0.5,
      ideological_opportunistic: 0.7,
      private_performative: -0.7,
      active_omissive: -1,
    },
    answers: BINARY,
    citation: { nl: { statute: "Opiumwet art. 2 · art. 3" } },
    tags: ["drugs", "severe"],
  },
  {
    id: "nl.vandalism",
    prompt:
      "Have you ever destroyed property that wasn't yours (graffiti, smashing, setting fire)?",
    format: "binary",
    severity: { nl: 18 },
    axes: {
      rebel_conformist: -0.6,
      victim_victimless: -0.4,
      self_other: 0.6,
      calculated_spontaneous: 0.4,
      private_performative: 0.2,
      active_omissive: -0.8,
    },
    answers: BINARY,
    citation: { nl: { statute: "Sr art. 350" } },
    tags: ["property"],
  },
  {
    id: "nl.perjury",
    prompt: "Have you ever lied under oath to police, court, or gemeente?",
    format: "binary",
    severity: { nl: 35 },
    axes: {
      principled_pragmatic: 0.7,
      calculated_spontaneous: -0.7,
      ideological_opportunistic: 0.3,
      private_performative: -0.5,
      realist_absolutist: -0.5,
    },
    answers: BINARY,
    citation: { nl: { statute: "Sr art. 207" } },
    tags: ["fraud", "legal"],
  },
  {
    id: "nl.witness-omission",
    prompt:
      "Have you ever witnessed someone clearly breaking the law (serious act) and said nothing to anyone?",
    format: "binary",
    severity: { nl: 8 },
    axes: {
      principled_pragmatic: 0.4,
      rebel_conformist: 0.3,
      self_other: 0.3,
      calculated_spontaneous: 0.2,
      private_performative: -0.6,
      active_omissive: 1,
    },
    answers: BINARY,
    citation: {
      nl: {
        statute: "Sr art. 136",
        note: "Omission only criminal for specific planned crimes.",
      },
    },
    tags: ["omission"],
  },
  {
    id: "nl.found-wallet",
    prompt:
      "A tourist drops their wallet with €400 in it. They walk away oblivious. You are the only one who saw.",
    format: "scenario",
    severity: { nl: 12 },
    answers: [
      {
        label: "Catch up and return it",
        intensity: 0,
        axes: {
          principled_pragmatic: -1,
          active_omissive: -1,
          upward_downward: -0.3,
        },
      },
      {
        label: "Take it to the nearest police station",
        intensity: 0,
        axes: {
          principled_pragmatic: -0.6,
          realist_absolutist: 0.5,
          active_omissive: -0.8,
        },
      },
      {
        label: "Leave it, assume someone else will",
        intensity: 0.4,
        axes: {
          active_omissive: 0.9,
          private_performative: -0.6,
          principled_pragmatic: 0.3,
        },
      },
      {
        label: "Pocket it and walk",
        intensity: 1,
        axes: {
          principled_pragmatic: 0.9,
          victim_victimless: -0.7,
          self_other: 0.9,
          ideological_opportunistic: 1,
          private_performative: -0.8,
          active_omissive: -0.7,
        },
      },
    ],
    citation: { nl: { statute: "Sr art. 321 (verduistering)" } },
    tags: ["scenario", "property"],
  },
  {
    id: "nl.billing-fraud",
    prompt:
      "Your boss tells you to bill a client for work that was never actually done. Your bonus depends on it.",
    format: "scenario",
    severity: { nl: 42 },
    answers: [
      {
        label: "Refuse and escalate to compliance",
        intensity: 0,
        axes: {
          principled_pragmatic: -1,
          upward_downward: -0.9,
          active_omissive: -1,
          private_performative: 0.3,
        },
      },
      {
        label: "Refuse quietly, don't report",
        intensity: 0.2,
        axes: {
          principled_pragmatic: -0.5,
          private_performative: -0.7,
          active_omissive: 0.4,
        },
      },
      {
        label: "Do it once, with excuses",
        intensity: 0.6,
        axes: {
          principled_pragmatic: 0.6,
          ideological_opportunistic: 0.7,
          calculated_spontaneous: -0.3,
          upward_downward: -0.3,
        },
      },
      {
        label: "Do it and enjoy the bonus",
        intensity: 0.9,
        axes: {
          principled_pragmatic: 1,
          victim_victimless: -0.5,
          self_other: 0.7,
          ideological_opportunistic: 1,
          private_performative: -0.5,
          active_omissive: -0.4,
        },
      },
    ],
    citation: { nl: { statute: "Sr art. 225 · art. 326" } },
    tags: ["scenario", "fraud", "work"],
  },
  {
    id: "nl.friend-confession",
    prompt:
      "A friend confesses to you, in confidence, that they committed a serious violent act against someone you both know.",
    format: "scenario",
    severity: { nl: 55 },
    answers: [
      {
        label: "Urge them to turn themselves in; report if they don't",
        intensity: 0,
        axes: {
          principled_pragmatic: -1,
          active_omissive: -1,
          victim_victimless: -0.7,
        },
      },
      {
        label: "Urge them to turn themselves in, but stay out",
        intensity: 0.3,
        axes: {
          principled_pragmatic: -0.4,
          active_omissive: 0.4,
          private_performative: -0.6,
        },
      },
      {
        label: "Tell them to get help; keep the secret",
        intensity: 0.6,
        axes: {
          active_omissive: 0.8,
          private_performative: -0.8,
          principled_pragmatic: 0.3,
        },
      },
      {
        label: "Say nothing to anyone. Not your business.",
        intensity: 1,
        axes: {
          active_omissive: 1,
          private_performative: -0.7,
          self_other: 0.5,
          principled_pragmatic: 0.8,
        },
      },
    ],
    tags: ["scenario", "omission", "violence"],
  },
  {
    id: "nl.landlord-eviction",
    prompt:
      "You're a landlord. Your tenant lost their job and can't pay rent for 3 months.",
    format: "scenario",
    severity: { nl: 20 },
    answers: [
      {
        label: "Waive rent until they find work",
        intensity: 0,
        axes: {
          principled_pragmatic: -1,
          self_other: -0.8,
          upward_downward: -0.8,
        },
      },
      {
        label: "Defer rent, keep them housed",
        intensity: 0.1,
        axes: {
          principled_pragmatic: -0.3,
          calculated_spontaneous: -0.6,
          upward_downward: -0.3,
        },
      },
      {
        label: "Follow contract: 30 days to vacate",
        intensity: 0.55,
        axes: {
          realist_absolutist: 0.9,
          upward_downward: 0.6,
          calculated_spontaneous: -0.5,
          principled_pragmatic: 0.3,
        },
      },
      {
        label: "Aggressive eviction, warn other landlords",
        intensity: 0.95,
        axes: {
          upward_downward: 1,
          self_other: 1,
          victim_victimless: -0.9,
          private_performative: 0.3,
          ideological_opportunistic: 0.6,
        },
      },
    ],
    tags: ["scenario", "power", "property"],
  },
  {
    id: "nl.doxx-colleague",
    prompt:
      "Someone publicly doxxes a colleague on social media. The colleague is visibly hurt. You see it on your timeline.",
    format: "scenario",
    severity: { nl: 22 },
    answers: [
      {
        label: "Publicly counter, support the colleague, report to platform",
        intensity: 0,
        axes: {
          principled_pragmatic: -1,
          private_performative: 0.6,
          active_omissive: -1,
          upward_downward: -0.5,
        },
      },
      {
        label: "Privately reach out, stay out of the public thread",
        intensity: 0.2,
        axes: {
          principled_pragmatic: -0.5,
          private_performative: -0.8,
          active_omissive: -0.3,
        },
      },
      {
        label: "Stay out entirely — internet drama",
        intensity: 0.65,
        axes: {
          active_omissive: 0.9,
          private_performative: -0.5,
          principled_pragmatic: 0.4,
        },
      },
      {
        label: "Share or like the doxx",
        intensity: 1,
        axes: {
          private_performative: 1,
          upward_downward: 1,
          self_other: 1,
          victim_victimless: -0.9,
          ideological_opportunistic: 0.6,
        },
      },
    ],
    citation: { nl: { statute: "Sr art. 285b (doxing, in force since 2024)" } },
    tags: ["scenario", "digital", "speech"],
  },
] as const;
